// <auto-generated />
using System;
using EmpresaAdmin.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpresaAdmin.Infra.Migrations
{
    [DbContext(typeof(FuncionarioDbContext))]
    [Migration("20241105223532_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EmpresaAdmin.Domain.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRemocao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailCorporativo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(400)");

                    b.Property<Guid?>("LiderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("NumeroChapa")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Telefones")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LiderId");

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("EmpresaAdmin.Domain.Models.Funcionario", b =>
                {
                    b.HasOne("EmpresaAdmin.Domain.Models.Funcionario", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId");

                    b.Navigation("Lider");
                });
#pragma warning restore 612, 618
        }
    }
}
